// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlBoTx.Net.EFCore;

#nullable disable

namespace SqlBoTx.Net.DbManager.Migrations
{
    [DbContext(typeof(SqlBotxDBContext))]
    partial class SqlBotxDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SqlBoTx.Net.Domain.Auth.RefreshToken", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("主键自增ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasComment("创建时间");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expires_at")
                        .HasComment("过期时间");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("bit")
                        .HasColumnName("is_revoked")
                        .HasComment("是否已撤销");

                    b.Property<string>("JwtId")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("jwt_id")
                        .HasComment("关联的JWT ID");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("token_hash")
                        .HasComment("令牌哈希值");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id")
                        .HasComment("用户ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("refresh_token", null, t =>
                        {
                            t.HasComment("刷新令牌");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.Organization.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("name")
                        .HasComment("组织名称");

                    b.Property<long?>("ParentId")
                        .HasColumnType("bigint")
                        .HasColumnName("parent_id")
                        .HasComment("父组织ID");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("organization", null, t =>
                        {
                            t.HasComment("组织结构");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.Organization.OrganizationRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("主键自增ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasComment("创建时间");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("description")
                        .HasComment("角色说明");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active")
                        .HasComment("是否启用");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("name")
                        .HasComment("角色名称");

                    b.Property<int>("RoleType")
                        .HasColumnType("int")
                        .HasColumnName("role_type")
                        .HasComment("角色类型");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order")
                        .HasComment("排序号");

                    b.HasKey("Id");

                    b.ToTable("organization_role", null, t =>
                        {
                            t.HasComment("组织角色");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.Organization.OrganizationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasComment("主键自增ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Admin")
                        .HasColumnType("bit")
                        .HasColumnName("admin")
                        .HasComment("系统用户");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date")
                        .HasComment("账号创建时间");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("email")
                        .HasComment("用户邮箱");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active")
                        .HasComment("账号是否启用");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login_date")
                        .HasComment("最后一次登录时间");

                    b.Property<string>("LoginAccount")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("login_account")
                        .HasComment("登录账号");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id")
                        .HasComment("所属组织ID");

                    b.Property<long>("OrganizationRoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_role_id")
                        .HasComment("所属角色ID");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("password")
                        .HasComment("登录密码");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)")
                        .HasColumnName("user_name")
                        .HasComment("用户显示名称，如：张三");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("OrganizationRoleId");

                    b.ToTable("organization_user", null, t =>
                        {
                            t.HasComment("问数系统用户");
                        });
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.Auth.RefreshToken", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.Organization.OrganizationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.Organization.Organization", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.Organization.Organization", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.Organization.OrganizationUser", b =>
                {
                    b.HasOne("SqlBoTx.Net.Domain.Organization.Organization", "Organization")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SqlBoTx.Net.Domain.Organization.OrganizationRole", "OrganizationRole")
                        .WithMany("Users")
                        .HasForeignKey("OrganizationRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organization");

                    b.Navigation("OrganizationRole");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.Organization.Organization", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("SqlBoTx.Net.Domain.Organization.OrganizationRole", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
